### ISSUE TITLE
Warning in new version of HA

### ISSUE THREAD

**Issue by eyalpost** [hllhll/HomeAssistant-ekon-local#31] opened 2024-07-29 16:27 UTC
Upgraded to HA 2024.7.3 and getting this warning whenever HA is starting up:
```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:365
integration: Climate (documentation, issues)
First occurred: 7:24:59 PM (3 occurrences)
Last logged: 7:24:59 PM

Entity None (<class 'custom_components.ekon-local.climate.EkonLocalClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please report it to the author of the 'ekon-local' custom integration
Entity None (<class 'custom_components.ekon-local.climate.EkonLocalClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please report it to the author of the 'ekon-local' custom integration
Entity None (<class 'custom_components.ekon-local.climate.EkonLocalClimate'>) implements HVACMode(s): auto, cool, dry, fan_only, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'ekon-local' custom integration
```

**Comment by hllhll** [comment] 2024-07-30 06:48
Duplicate of #28 Fix exists, have fun :)

**Comment by hllhll** [comment] 2024-07-30 06:49
I might be mistaken, If you can please check the other closed, reported issues, thanks

**Comment by eyalpost** [comment] 2024-07-30 07:27
Which other issue? The one I reported before was fixed. This is a different issue

**Comment by hllhll** [comment] 2024-07-30 07:41
Yeah I've mistaken it as something I remembered from some time back, which is not the same

Does the integration still works BTW? These are just warnings?

**Comment by eyalpost** [comment] 2024-07-30 08:08
Yes it does work.
cc @sr01 which hopefully can verify whether it happens in the new version or not

**Closed as completed** 2024-08-25 11:45 UTC
Labels: bug, compatibility
